### ISSUE TITLE
Crash, potentially related to labelled-old expresions

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#128]
> Created by **@mschwerhoff** on 2016-04-04 19:40

```
#!text

method Foo(this: Ref)
{
  var i: Int;
  i := 10;

  var check: Bool
  check := false;

  while(i > 0)
    invariant [true, check ==> (0 <= i && i < old[l](i))]
  {
    label l
    i := i - 1
    check := true
  }
}
```

```
#!text
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at viper.carbon.modules.impls.DefaultExpModule.translateExp(DefaultExpModule.scala:69)
	at viper.carbon.modules.impls.DefaultExpModule.translateExp(DefaultExpModule.scala:190)
	at viper.carbon.modules.impls.DefaultExhaleModule.exhaleExp(DefaultExhaleModule.scala:90)
	at viper.carbon.modules.impls.DefaultExhaleModule$$anonfun$viper$carbon$modules$impls$DefaultExhaleModule$$exhaleConnective$1.apply(DefaultExhaleModule.scala:76)
	at viper.carbon.modules.impls.DefaultExhaleModule$$anonfun$viper$carbon$modules$impls$DefaultExhaleModule$$exhaleConnective$1.apply(DefaultExhaleModule.scala:76)
      ...
```

**Comment by gauravpartha** [comment]
This has been fixed in 2b9ac113e58b2091a818f8cae9cce2826d2a106d.

Carbon behaves differently than Silicon here. Silicon reports that the invariant is not preserved, while Carbon additionally reports that the label in the invariant may not be reached. The reason is that Carbon checks that the invariant is well-defined for any values assigned to the written variables and since the label is defined inside the body for the first time, this information is not visible in the definedness check.

Currently, I think that some such error regarding the label should be reported. It seems strange to use a label that is defined only inside the body in the invariant if one considers loops modularly. In this particular case, what does it mean to inhale `[true, check ==> (0 <= i && i < old[l](i))]` at the beginning of the loop body? In an executable semantics label `l` will have been defined whenever check is true and one could think of `l` referring to the label in the previous iteration. However, I don't think we have ever agreed on such a semantics. Moreover, from a modular perspective it is not known that `l` is defined iff check is true (and there is no way to even express this as an expression).
