### ISSUE TITLE
Test all/assume/assume10QPwand.sil causes Boogie errors

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#255]
> Created by **@mschwerhoff** on 2018-10-11 15:55
> Last updated on 2019-07-27 02:34

```text
java.lang.RuntimeException: missing translation for inhaling of (forall x: Ref, y: Ref, z: Ref :: { (x in xs),(y in ys),(z in zs) } (x in xs) && ((y in ys) && (z in zs)) ==> acc(x.f, write) && (acc(y.f, write) && acc(z.f, write)) --* acc(p(x, y, z), write))
   at scala.sys.package$.error(package.scala:27)
   at viper.carbon.modules.impls.DefaultInhaleModule.viper$carbon$modules$impls$DefaultInhaleModule$$inhaleConnective(DefaultInhaleModule.scala:74)
   at viper.carbon.modules.impls.DefaultInhaleModule$$anonfun$inhale$1.apply(DefaultInhaleModule.scala:33)
   at viper.carbon.modules.impls.DefaultInhaleModule$$anonfun$inhale$1.apply(DefaultInhaleModule.scala:33)
   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
   at scala.collection.immutable.List.foreach(List.scala:381)
   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
   at scala.collection.immutable.List.map(List.scala:285)
   at viper.carbon.modules.impls.DefaultInhaleModule.inhale(DefaultInhaleModule.scala:33)
   ...
```

**Comment by fpoli** [comment]
Indeed, Carbon doesn't seem to support quantified magic wands. I get the same kind of Java exception with the following program.

```
predicate P(x: Int)

method lemma()
    requires forall x: Int :: P(x) --* P(x)
```
