### ISSUE TITLE
Internal Error when using exists

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#274]
> Created by **@fpoli** on 2019-05-21 14:37
> Last updated on 2019-11-04 10:39

The following program crashes with `Internal Error: variable nn is not defined`:

```
field neighbour: Set[Ref]
field visited: Bool

predicate access_fields(node: Ref) {
    acc(node.neighbour, 1/2) && acc(node.visited)
}

method foo(curr_node: Ref, all_nodes: Set[Ref])
    requires forall n:Ref :: {n in all_nodes} n in all_nodes ==> (access_fields(n) && unfolding access_fields(n) in n.neighbour subset all_nodes)
    requires curr_node in all_nodes
    requires exists nn:Ref :: (nn in all_nodes && nn != curr_node && unfolding access_fields(nn) in !nn.visited)
```

However, the following is accepted:

```
field neighbour: Set[Ref]
field visited: Bool

predicate access_fields(node: Ref) {
    acc(node.neighbour, 1/2) && acc(node.visited)
}

method foo(curr_node: Ref, all_nodes: Set[Ref])
    requires forall n:Ref :: {n in all_nodes} n in all_nodes ==> (access_fields(n) && unfolding access_fields(n) in n.neighbour subset all_nodes)
    requires curr_node in all_nodes
    requires !forall nn:Ref :: !(nn in all_nodes && nn != curr_node && unfolding access_fields(nn) in !nn.visited)
```

Stacktrace:

```
Exception in thread "main" java.lang.RuntimeException: Internal Error: variable nn is not defined.
	at scala.sys.package$.error(package.scala:26)
	at viper.carbon.verifier.Environment.get(Environment.scala:53)
	at viper.carbon.modules.impls.DefaultExpModule.translateLocalVar(DefaultExpModule.scala:285)
	at viper.carbon.modules.impls.DefaultExpModule.translateExp(DefaultExpModule.scala:68)
	at viper.carbon.modules.impls.DefaultHeapModule.$anonfun$predicateMask$1(DefaultHeapModule.scala:364)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at viper.carbon.modules.impls.DefaultHeapModule.predicateMask(DefaultHeapModule.scala:364)
	at viper.carbon.modules.impls.DefaultHeapModule.addPermissionToPMask(DefaultHeapModule.scala:503)
	at viper.carbon.modules.impls.DefaultHeapModule.freeAssumptions(DefaultHeapModule.scala:474)
	at viper.carbon.modules.impls.DefaultExpModule.$anonfun$allFreeAssumptions$1(DefaultExpModule.scala:561)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at viper.carbon.modules.impls.DefaultExpModule.translate$2(DefaultExpModule.scala:561)
	at viper.carbon.modules.impls.DefaultExpModule.allFreeAssumptions(DefaultExpModule.scala:594)
	at viper.carbon.modules.impls.DefaultExpModule.$anonfun$allFreeAssumptions$3(DefaultExpModule.scala:582)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:738)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:737)
	at viper.carbon.modules.impls.DefaultExpModule.translate$2(DefaultExpModule.scala:581)
	at viper.carbon.modules.impls.DefaultExpModule.allFreeAssumptions(DefaultExpModule.scala:594)
	at viper.carbon.modules.impls.DefaultExpModule.$anonfun$allFreeAssumptions$3(DefaultExpModule.scala:582)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:738)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:737)
	at viper.carbon.modules.impls.DefaultExpModule.translate$2(DefaultExpModule.scala:581)
	at viper.carbon.modules.impls.DefaultExpModule.allFreeAssumptions(DefaultExpModule.scala:594)
	at viper.carbon.modules.impls.DefaultExpModule.$anonfun$allFreeAssumptions$3(DefaultExpModule.scala:582)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:738)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:737)
	at viper.carbon.modules.impls.DefaultExpModule.translate$2(DefaultExpModule.scala:581)
	at viper.carbon.modules.impls.DefaultExpModule.allFreeAssumptions(DefaultExpModule.scala:594)
	at viper.carbon.modules.impls.DefaultInhaleModule.$anonfun$inhale$2(DefaultInhaleModule.scala:42)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.immutable.List.map(List.scala:294)
	at viper.carbon.modules.impls.DefaultInhaleModule.inhale(DefaultInhaleModule.scala:42)
	at viper.carbon.modules.impls.DefaultExpModule.checkDefinednessOfSpecAndInhale(DefaultExpModule.scala:511)
	at viper.carbon.modules.ExpModule.$anonfun$checkDefinednessOfInhaleSpecAndInhale$1(ExpModule.scala:77)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at viper.carbon.modules.ExpModule.checkDefinednessOfInhaleSpecAndInhale(ExpModule.scala:76)
	at viper.carbon.modules.ExpModule.checkDefinednessOfInhaleSpecAndInhale$(ExpModule.scala:74)
	at viper.carbon.modules.impls.DefaultExpModule.checkDefinednessOfInhaleSpecAndInhale(DefaultExpModule.scala:22)
	at viper.carbon.modules.impls.DefaultMainModule.translateMethodDeclPre(DefaultMainModule.scala:189)
	at viper.carbon.modules.impls.DefaultMainModule.translateMethodDecl(DefaultMainModule.scala:104)
	at viper.carbon.modules.impls.DefaultMainModule.$anonfun$translate$5(DefaultMainModule.scala:67)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at viper.carbon.modules.impls.DefaultMainModule.translate(DefaultMainModule.scala:67)
	at viper.carbon.CarbonVerifier.verify(CarbonVerifier.scala:134)
	at viper.silver.frontend.DefaultFrontend.verification(Frontend.scala:242)
	at viper.silver.frontend.DefaultFrontend.verification$(Frontend.scala:240)
	at viper.carbon.CarbonFrontend.verification(Carbon.scala:26)
	at viper.silver.frontend.DefaultPhases.$anonfun$phases$5(Frontend.scala:98)
	at viper.silver.frontend.Frontend.$anonfun$run$1(Frontend.scala:59)
	at viper.silver.frontend.Frontend.$anonfun$run$1$adapted(Frontend.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at viper.silver.frontend.Frontend.run(Frontend.scala:59)
	at viper.silver.frontend.Frontend.run$(Frontend.scala:58)
	at viper.carbon.CarbonFrontend.run(Carbon.scala:26)
	at viper.silver.frontend.SilFrontend.execute(SilFrontend.scala:153)
	at viper.silver.frontend.SilFrontend.execute$(SilFrontend.scala:131)
	at viper.carbon.CarbonFrontend.execute(Carbon.scala:26)
	at viper.carbon.Carbon$.main(Carbon.scala:20)
	at viper.carbon.Carbon.main(Carbon.scala)
```

**Comment by gauravpartha** [comment]
Fixed in commit cfab5877b764aab7298049
