### ISSUE TITLE
Boogie Path in Windows broken

### ISSUE THREAD

**Issue by ArmborstL** [viperproject/carbon#509]
I'm using VerCors on Windows.
Trying to run a VerCors-generated Viper file through Carbon, I get _"Exception in thread "main" java.io.IOException: Cannot run program "C:\abc\\"C:\def\Boogie.exe"": CreateProcess error=2, The system cannot find the file specified"_, where `C:\abc\` represents my current directory, and `C:\def\Boogie.exe` the valid path to the Boogie.exe, as specified by the `BOOGIE_EXE` environment variable. 
It looks to me like some paths are constructed incorrectly.

VerCors is using commit d7ac8b000e1123a72cbdda0c7679ab88ca8a52d4 of Carbon.
Carbon is invoked via `java -Xmx2G -Xss32m -cp <classpath> viper.carbon.Carbon <filename>`.

<details>
<summary> Full stack trace </summary>

```
Exception in thread "main" java.io.IOException: Cannot run program "C:\abc\"C:\def\Boogie.exe"": CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at viper.carbon.verifier.BoogieInterface.run(BoogieInterface.scala:167)
        at viper.carbon.verifier.BoogieInterface.invokeBoogie(BoogieInterface.scala:91)
        at viper.carbon.verifier.BoogieInterface.invokeBoogie$(BoogieInterface.scala:82)
        at viper.carbon.CarbonVerifier.invokeBoogie(CarbonVerifier.scala:26)
        at viper.carbon.CarbonVerifier.verify(CarbonVerifier.scala:227)
        at viper.silver.frontend.DefaultFrontend.verification(Frontend.scala:267)
        at viper.silver.frontend.DefaultFrontend.verification$(Frontend.scala:265)
        at viper.carbon.CarbonFrontend.viper$silver$frontend$SilFrontend$$super$verification(Carbon.scala:26)
        at viper.silver.frontend.SilFrontend.verification(SilFrontend.scala:253)
        at viper.silver.frontend.SilFrontend.verification$(SilFrontend.scala:226)
        at viper.carbon.CarbonFrontend.verification(Carbon.scala:26)
        at viper.silver.frontend.DefaultPhases.$anonfun$Verification$1(Frontend.scala:117)
        at viper.silver.frontend.Frontend.$anonfun$runAllPhases$1(Frontend.scala:62)
        at viper.silver.frontend.Frontend.$anonfun$runAllPhases$1$adapted(Frontend.scala:60)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.silver.frontend.Frontend.runAllPhases(Frontend.scala:60)
        at viper.silver.frontend.Frontend.runAllPhases$(Frontend.scala:59)
        at viper.carbon.CarbonFrontend.runAllPhases(Carbon.scala:26)
        at viper.silver.frontend.SilFrontend.execute(SilFrontend.scala:188)
        at viper.silver.frontend.SilFrontend.execute$(SilFrontend.scala:165)
        at viper.carbon.CarbonFrontend.execute(Carbon.scala:26)
        at viper.carbon.Carbon$.main(Carbon.scala:20)
        at viper.carbon.Carbon.main(Carbon.scala)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 24 more
```
</details>

**Comment by gauravpartha** [comment]
I think the problem is that you have stored the path to the Boogie executable in the `BOOGIE_EXE` environment variable using quotation marks (i.e. `"C:\def\Boogie.exe"` instead of `C:\def\Boogie.exe`). I was able to reproduce the error that you posted after adding the quotation marks to my `BOOGIE_EXE` environment variable. Without quotation marks, the command works as expected. Does it work for you if you remove the quotes?

**Comment by ArmborstL** [comment]
Yes, that seems to fix the issue. I thought this might cause problems if the path has spaces. But even if the path in `BOOGIE_EXE` contains spaces, it seems to work.
Thanks for looking into it 👍
