### ISSUE TITLE
Carbon crashes if Silver program contains an empty constraining block

### ISSUE THREAD

**Issue by viper-admin** [viperproject/carbon#62]
> Created by **@vakaras** on 2015-07-17 12:28
> Last updated on 2015-07-17 12:32

Example Silver program:
```
#!Silver
method test()
{
  var k: Perm
  constraining (k) {
  }
}
```

Error message:
```
[info] - all/issues/carbon/0062.sil [carbon-Silver] *** FAILED *** (714 milliseconds)
[info]   java.lang.AssertionError: assertion failed: Translation of constraining(k) {
[info] } is not defined
[info]   at scala.Predef$.assert(Predef.scala:179)
[info]   at viper.carbon.modules.impls.DefaultStmtModule.translateStmt(DefaultStmtModule.scala:219)
[info]   at viper.carbon.modules.impls.DefaultStmtModule$$anonfun$translateStmt$1.apply(DefaultStmtModule.scala:192)
[info]   at viper.carbon.modules.impls.DefaultStmtModule$$anonfun$translateStmt$1.apply(DefaultStmtModule.scala:192)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[info]   at scala.collection.immutable.List.foreach(List.scala:318)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[info]   at viper.carbon.modules.impls.DefaultStmtModule.translateStmt(DefaultStmtModule.scala:192)
[info]   ...
```

The problem seems to be that the empty `constraining` block does not trigger any component to produce output. As a result, the check that statement was translated fails.

**Comment by gauravpartha** [comment]
Constraining blocks have been removed from Viper in commit viperproject/silver@b2f869dbac.
